language: go

install:
  - npm install
  - bundle install

go_import_path: github.com/snikch/goodman
script:
  - go test github.com/snikch/goodman/{,/transaction,/hooks}
  - bundle exec cucumber
  - make -C example dredd
